name = "AffineScriptPkg"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
julia = "1.10"
HTTP = "1.10"
JSON3 = "1.14"
